---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeswarm
    app.kubernetes.io/managed-by: kustomize
  name: swarmevent-admin-role
rules:
  - apiGroups:
      - kubeswarm
    resources:
      - swarmevents
    verbs:
      - "*"
  - apiGroups:
      - kubeswarm
    resources:
      - swarmevents/status
    verbs:
      - get
