---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeswarm
    app.kubernetes.io/managed-by: kustomize
  name: swarmagent-viewer-role
rules:
  - apiGroups:
      - kubeswarm
    resources:
      - swarmagents
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeswarm
    resources:
      - swarmagents/status
    verbs:
      - get
