/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TokenUsage records the number of tokens consumed by a single step or the whole pipeline.
type TokenUsage struct {
	// InputTokens is the total number of prompt/input tokens sent to the LLM.
	InputTokens int64 `json:"inputTokens"`
	// OutputTokens is the total number of completion/output tokens generated by the LLM.
	OutputTokens int64 `json:"outputTokens"`
	// TotalTokens is InputTokens + OutputTokens, provided for convenient display.
	TotalTokens int64 `json:"totalTokens"`
}

// SwarmFlowStepPhase describes the execution state of a single pipeline step.
// +kubebuilder:validation:Enum=Pending;WarmingUp;Running;Validating;Succeeded;Failed;Skipped
type SwarmFlowStepPhase string

const (
	SwarmFlowStepPhasePending SwarmFlowStepPhase = "Pending"
	// SwarmFlowStepPhaseWarmingUp means the step is waiting for its assigned agent's pods to
	// become ready after a scale-from-zero event. Transitions to Running once ready.
	SwarmFlowStepPhaseWarmingUp SwarmFlowStepPhase = "WarmingUp"
	SwarmFlowStepPhaseRunning   SwarmFlowStepPhase = "Running"
	// SwarmFlowStepPhaseValidating means the step completed and is awaiting output validation.
	SwarmFlowStepPhaseValidating SwarmFlowStepPhase = "Validating"
	SwarmFlowStepPhaseSucceeded  SwarmFlowStepPhase = "Succeeded"
	SwarmFlowStepPhaseFailed     SwarmFlowStepPhase = "Failed"
	// SwarmFlowStepPhaseSkipped means the step was bypassed because its If condition evaluated to false.
	SwarmFlowStepPhaseSkipped SwarmFlowStepPhase = "Skipped"
)

// LoopSpec defines loop behaviour for a pipeline step.
type LoopSpec struct {
	// Condition is a Go template expression evaluated after each iteration.
	// The step repeats while this evaluates to a truthy value ("true", non-empty, non-"false", non-"0").
	// Example: "{{ gt (len .steps.collect.output) 0 }}"
	// +kubebuilder:validation:Required
	Condition string `json:"condition"`

	// MaxIterations caps the number of loop repetitions to prevent infinite loops.
	// +kubebuilder:default=10
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=100
	MaxIterations int `json:"maxIterations,omitempty"`
}

// StepContextPolicy controls how a step's output is prepared before injection
// into downstream step prompts via "{{ .steps.<name>.output }}".
type StepContextPolicy struct {
	// Strategy determines how the output is handled before downstream injection.
	// full: verbatim injection wrapped in <swarm:step-output> (default, current behaviour).
	// compress: output is summarised by an LLM call before injection.
	// extract: a JSONPath or regexp is applied; only the matched value is injected.
	// none: nothing is injected; "{{ .steps.<name>.output }}" resolves to "".
	// +kubebuilder:validation:Enum=full;compress;extract;none
	// +kubebuilder:default=full
	Strategy string `json:"strategy"`

	// Compress configures LLM-based summarisation. Only used when strategy=compress.
	// +optional
	Compress *ContextCompressConfig `json:"compress,omitempty"`

	// Extract configures field or pattern extraction. Only used when strategy=extract.
	// +optional
	Extract *ContextExtractConfig `json:"extract,omitempty"`
}

// ContextCompressConfig configures the compression LLM call.
type ContextCompressConfig struct {
	// TargetTokens is the advisory token budget for the compressed output.
	// 0 means no explicit budget — the agent uses its own judgement.
	// +optional
	TargetTokens int `json:"targetTokens,omitempty"`

	// Model is the model used for compression.
	// Defaults to the pipeline's configured model when unset.
	// A cheaper model (e.g. claude-haiku-4-5) is recommended.
	// +optional
	Model string `json:"model,omitempty"`

	// Prompt overrides the system prompt sent to the compression LLM.
	// The placeholder "{{ .targetTokens }}" is available.
	// When unset, a built-in summarisation prompt is used.
	// +optional
	Prompt string `json:"prompt,omitempty"`
}

// ContextExtractConfig configures field or pattern extraction.
type ContextExtractConfig struct {
	// Path is evaluated as a JSONPath expression when the step output is valid JSON,
	// or as a Go regexp (first capture group) for prose output.
	// +kubebuilder:validation:Required
	Path string `json:"path"`
}

// SwarmFlowStepStatus captures the observed state of a single step.
type SwarmFlowStepStatus struct {
	// Name matches the step name in spec.
	Name string `json:"name"`
	// Phase is the current execution phase.
	Phase SwarmFlowStepPhase `json:"phase"`
	// TaskID is the Redis stream message ID of the submitted task, used to
	// correlate results from the agent-tasks-results stream.
	TaskID string `json:"taskID,omitempty"`
	// Output is the agent's response after context policy has been applied.
	// For strategy=full this is the verbatim agent output (current behaviour).
	// For strategy=compress this is the compressed summary.
	// For strategy=extract this is the extracted value.
	// For strategy=none this is empty.
	Output string `json:"output,omitempty"`

	// RawOutput is the original unprocessed agent output.
	// Only populated when contextPolicy.strategy is compress or extract, so
	// downstream steps can access pre-policy output via "{{ .steps.<name>.rawOutput }}".
	// +optional
	RawOutput string `json:"rawOutput,omitempty"`

	// CompressionTokens is the token count of the compressed output.
	// Only populated when contextPolicy.strategy=compress.
	// +optional
	CompressionTokens int `json:"compressionTokens,omitempty"`

	// OutputJSON is the agent's response as a JSON string, populated when the step
	// has an OutputSchema and the response is valid JSON. Downstream steps can
	// reference fields via "{{ .steps.<name>.data.<field> }}".
	OutputJSON string `json:"outputJSON,omitempty"`
	// StartTime is when the step started executing.
	StartTime *metav1.Time `json:"startTime,omitempty"`
	// CompletionTime is when the step finished (success or failure).
	CompletionTime *metav1.Time `json:"completionTime,omitempty"`
	// Message holds a human-readable status detail.
	Message string `json:"message,omitempty"`
	// Iterations is the number of times this step has been executed (for loop steps).
	Iterations int `json:"iterations,omitempty"`
	// TokenUsage reports the tokens consumed by this step's LLM calls.
	TokenUsage *TokenUsage `json:"tokenUsage,omitempty"`
	// CostUSD is the estimated dollar cost of this step's LLM calls, calculated
	// using the operator's configured CostProvider. Decimal string; empty for unknown/local models.
	CostUSD string `json:"costUSD,omitempty"`
	// ValidationAttempts counts how many times output validation has been run on this step.
	// Incremented on each validation attempt; reset when the step is retried from Pending.
	ValidationAttempts int `json:"validationAttempts,omitempty"`
	// ValidationMessage holds the most recent validation failure reason.
	// Cleared when validation passes.
	ValidationMessage string `json:"validationMessage,omitempty"`
	// Artifacts maps artifact names to their storage URLs or local paths.
	// Populated after the step completes when spec.artifactStore is configured.
	// Downstream steps reference artifacts via "{{ .steps.<name>.artifacts.<key> }}".
	Artifacts map[string]string `json:"artifacts,omitempty"`

	// ResolvedAgent is the SwarmAgent name selected by a registry lookup for this step.
	// Empty when the step uses a static role reference.
	// +optional
	ResolvedAgent string `json:"resolvedAgent,omitempty"`

	// SelectedCapability is the capability ID chosen by the router LLM.
	// Only set for the synthetic "route" step in routed-mode runs.
	// +optional
	SelectedCapability string `json:"selectedCapability,omitempty"`

	// RoutingReason is the router LLM's one-sentence explanation for its choice.
	// Only set for the synthetic "route" step in routed-mode runs.
	// +optional
	RoutingReason string `json:"routingReason,omitempty"`
}
