//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCapability) DeepCopyInto(out *AgentCapability) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InputSchema != nil {
		in, out := &in.InputSchema, &out.InputSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.OutputSchema != nil {
		in, out := &in.OutputSchema, &out.OutputSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCapability.
func (in *AgentCapability) DeepCopy() *AgentCapability {
	if in == nil {
		return nil
	}
	out := new(AgentCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentConnection) DeepCopyInto(out *AgentConnection) {
	*out = *in
	if in.AgentRef != nil {
		in, out := &in.AgentRef, &out.AgentRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.CapabilityRef != nil {
		in, out := &in.CapabilityRef, &out.CapabilityRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentConnection.
func (in *AgentConnection) DeepCopy() *AgentConnection {
	if in == nil {
		return nil
	}
	out := new(AgentConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentFleetEntry) DeepCopyInto(out *AgentFleetEntry) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentFleetEntry.
func (in *AgentFleetEntry) DeepCopy() *AgentFleetEntry {
	if in == nil {
		return nil
	}
	out := new(AgentFleetEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentGuardrails) DeepCopyInto(out *AgentGuardrails) {
	*out = *in
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = new(ToolPermissions)
		(*in).DeepCopyInto(*out)
	}
	if in.BudgetRef != nil {
		in, out := &in.BudgetRef, &out.BudgetRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(GuardrailLimits)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentGuardrails.
func (in *AgentGuardrails) DeepCopy() *AgentGuardrails {
	if in == nil {
		return nil
	}
	out := new(AgentGuardrails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentHealthCheck) DeepCopyInto(out *AgentHealthCheck) {
	*out = *in
	if in.NotifyRef != nil {
		in, out := &in.NotifyRef, &out.NotifyRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentHealthCheck.
func (in *AgentHealthCheck) DeepCopy() *AgentHealthCheck {
	if in == nil {
		return nil
	}
	out := new(AgentHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLogging) DeepCopyInto(out *AgentLogging) {
	*out = *in
	if in.Redaction != nil {
		in, out := &in.Redaction, &out.Redaction
		*out = new(LogRedactionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLogging.
func (in *AgentLogging) DeepCopy() *AgentLogging {
	if in == nil {
		return nil
	}
	out := new(AgentLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLoopMemory) DeepCopyInto(out *AgentLoopMemory) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLoopMemory.
func (in *AgentLoopMemory) DeepCopy() *AgentLoopMemory {
	if in == nil {
		return nil
	}
	out := new(AgentLoopMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLoopPolicy) DeepCopyInto(out *AgentLoopPolicy) {
	*out = *in
	if in.Compression != nil {
		in, out := &in.Compression, &out.Compression
		*out = new(LoopCompressionConfig)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(AgentLoopMemory)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLoopPolicy.
func (in *AgentLoopPolicy) DeepCopy() *AgentLoopPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentLoopPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMetrics) DeepCopyInto(out *AgentMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMetrics.
func (in *AgentMetrics) DeepCopy() *AgentMetrics {
	if in == nil {
		return nil
	}
	out := new(AgentMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentObservability) DeepCopyInto(out *AgentObservability) {
	*out = *in
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(AgentHealthCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(AgentLogging)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(AgentMetrics)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentObservability.
func (in *AgentObservability) DeepCopy() *AgentObservability {
	if in == nil {
		return nil
	}
	out := new(AgentObservability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPlugins) DeepCopyInto(out *AgentPlugins) {
	*out = *in
	if in.LLM != nil {
		in, out := &in.LLM, &out.LLM
		*out = new(PluginEndpoint)
		(*in).DeepCopyInto(*out)
	}
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = new(PluginEndpoint)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPlugins.
func (in *AgentPlugins) DeepCopy() *AgentPlugins {
	if in == nil {
		return nil
	}
	out := new(AgentPlugins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentPrompt) DeepCopyInto(out *AgentPrompt) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(SystemPromptSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentPrompt.
func (in *AgentPrompt) DeepCopy() *AgentPrompt {
	if in == nil {
		return nil
	}
	out := new(AgentPrompt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntime) DeepCopyInto(out *AgentRuntime) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(SwarmAgentAutoscaling)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Loop != nil {
		in, out := &in.Loop, &out.Loop
		*out = new(AgentLoopPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntime.
func (in *AgentRuntime) DeepCopy() *AgentRuntime {
	if in == nil {
		return nil
	}
	out := new(AgentRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTools) DeepCopyInto(out *AgentTools) {
	*out = *in
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = make([]MCPToolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Webhooks != nil {
		in, out := &in.Webhooks, &out.Webhooks
		*out = make([]WebhookToolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTools.
func (in *AgentTools) DeepCopy() *AgentTools {
	if in == nil {
		return nil
	}
	out := new(AgentTools)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactSpec) DeepCopyInto(out *ArtifactSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactSpec.
func (in *ArtifactSpec) DeepCopy() *ArtifactSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactStoreGCSSpec) DeepCopyInto(out *ArtifactStoreGCSSpec) {
	*out = *in
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactStoreGCSSpec.
func (in *ArtifactStoreGCSSpec) DeepCopy() *ArtifactStoreGCSSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactStoreGCSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactStoreLocalSpec) DeepCopyInto(out *ArtifactStoreLocalSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactStoreLocalSpec.
func (in *ArtifactStoreLocalSpec) DeepCopy() *ArtifactStoreLocalSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactStoreLocalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactStoreS3Spec) DeepCopyInto(out *ArtifactStoreS3Spec) {
	*out = *in
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactStoreS3Spec.
func (in *ArtifactStoreS3Spec) DeepCopy() *ArtifactStoreS3Spec {
	if in == nil {
		return nil
	}
	out := new(ArtifactStoreS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactStoreSpec) DeepCopyInto(out *ArtifactStoreSpec) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(ArtifactStoreLocalSpec)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(ArtifactStoreS3Spec)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(ArtifactStoreGCSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactStoreSpec.
func (in *ArtifactStoreSpec) DeepCopy() *ArtifactStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BearerAuth) DeepCopyInto(out *BearerAuth) {
	*out = *in
	in.SecretKeyRef.DeepCopyInto(&out.SecretKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BearerAuth.
func (in *BearerAuth) DeepCopy() *BearerAuth {
	if in == nil {
		return nil
	}
	out := new(BearerAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextCompressConfig) DeepCopyInto(out *ContextCompressConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextCompressConfig.
func (in *ContextCompressConfig) DeepCopy() *ContextCompressConfig {
	if in == nil {
		return nil
	}
	out := new(ContextCompressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextExtractConfig) DeepCopyInto(out *ContextExtractConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextExtractConfig.
func (in *ContextExtractConfig) DeepCopy() *ContextExtractConfig {
	if in == nil {
		return nil
	}
	out := new(ContextExtractConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddingConfig) DeepCopyInto(out *EmbeddingConfig) {
	*out = *in
	if in.APIKeyRef != nil {
		in, out := &in.APIKeyRef, &out.APIKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddingConfig.
func (in *EmbeddingConfig) DeepCopy() *EmbeddingConfig {
	if in == nil {
		return nil
	}
	out := new(EmbeddingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuardrailLimits) DeepCopyInto(out *GuardrailLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuardrailLimits.
func (in *GuardrailLimits) DeepCopy() *GuardrailLimits {
	if in == nil {
		return nil
	}
	out := new(GuardrailLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexedCapability) DeepCopyInto(out *IndexedCapability) {
	*out = *in
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexedCapability.
func (in *IndexedCapability) DeepCopy() *IndexedCapability {
	if in == nil {
		return nil
	}
	out := new(IndexedCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogRedactionPolicy) DeepCopyInto(out *LogRedactionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogRedactionPolicy.
func (in *LogRedactionPolicy) DeepCopy() *LogRedactionPolicy {
	if in == nil {
		return nil
	}
	out := new(LogRedactionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoopCompressionConfig) DeepCopyInto(out *LoopCompressionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoopCompressionConfig.
func (in *LoopCompressionConfig) DeepCopy() *LoopCompressionConfig {
	if in == nil {
		return nil
	}
	out := new(LoopCompressionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoopSpec) DeepCopyInto(out *LoopSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoopSpec.
func (in *LoopSpec) DeepCopy() *LoopSpec {
	if in == nil {
		return nil
	}
	out := new(LoopSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPBinding) DeepCopyInto(out *MCPBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPBinding.
func (in *MCPBinding) DeepCopy() *MCPBinding {
	if in == nil {
		return nil
	}
	out := new(MCPBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPHeader) DeepCopyInto(out *MCPHeader) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPHeader.
func (in *MCPHeader) DeepCopy() *MCPHeader {
	if in == nil {
		return nil
	}
	out := new(MCPHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerAuth) DeepCopyInto(out *MCPServerAuth) {
	*out = *in
	if in.Bearer != nil {
		in, out := &in.Bearer, &out.Bearer
		*out = new(BearerAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.MTLS != nil {
		in, out := &in.MTLS, &out.MTLS
		*out = new(MTLSAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerAuth.
func (in *MCPServerAuth) DeepCopy() *MCPServerAuth {
	if in == nil {
		return nil
	}
	out := new(MCPServerAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPToolSpec) DeepCopyInto(out *MCPToolSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(MCPServerAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]MCPHeader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPToolSpec.
func (in *MCPToolSpec) DeepCopy() *MCPToolSpec {
	if in == nil {
		return nil
	}
	out := new(MCPToolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MTLSAuth) DeepCopyInto(out *MTLSAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MTLSAuth.
func (in *MTLSAuth) DeepCopy() *MTLSAuth {
	if in == nil {
		return nil
	}
	out := new(MTLSAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotifyChannelSpec) DeepCopyInto(out *NotifyChannelSpec) {
	*out = *in
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookChannelSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackChannelSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotifyChannelSpec.
func (in *NotifyChannelSpec) DeepCopy() *NotifyChannelSpec {
	if in == nil {
		return nil
	}
	out := new(NotifyChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotifyDispatchResult) DeepCopyInto(out *NotifyDispatchResult) {
	*out = *in
	if in.LastFiredAt != nil {
		in, out := &in.LastFiredAt, &out.LastFiredAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotifyDispatchResult.
func (in *NotifyDispatchResult) DeepCopy() *NotifyDispatchResult {
	if in == nil {
		return nil
	}
	out := new(NotifyDispatchResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginEndpoint) DeepCopyInto(out *PluginEndpoint) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(PluginTLSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginEndpoint.
func (in *PluginEndpoint) DeepCopy() *PluginEndpoint {
	if in == nil {
		return nil
	}
	out := new(PluginEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginTLSConfig) DeepCopyInto(out *PluginTLSConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginTLSConfig.
func (in *PluginTLSConfig) DeepCopy() *PluginTLSConfig {
	if in == nil {
		return nil
	}
	out := new(PluginTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptFragment) DeepCopyInto(out *PromptFragment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptFragment.
func (in *PromptFragment) DeepCopy() *PromptFragment {
	if in == nil {
		return nil
	}
	out := new(PromptFragment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptFragments) DeepCopyInto(out *PromptFragments) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptFragments.
func (in *PromptFragments) DeepCopy() *PromptFragments {
	if in == nil {
		return nil
	}
	out := new(PromptFragments)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisMemoryConfig) DeepCopyInto(out *RedisMemoryConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisMemoryConfig.
func (in *RedisMemoryConfig) DeepCopy() *RedisMemoryConfig {
	if in == nil {
		return nil
	}
	out := new(RedisMemoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryLookupSpec) DeepCopyInto(out *RegistryLookupSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RegistryRef != nil {
		in, out := &in.RegistryRef, &out.RegistryRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryLookupSpec.
func (in *RegistryLookupSpec) DeepCopy() *RegistryLookupSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryLookupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackChannelSpec) DeepCopyInto(out *SlackChannelSpec) {
	*out = *in
	in.WebhookURLFrom.DeepCopyInto(&out.WebhookURLFrom)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackChannelSpec.
func (in *SlackChannelSpec) DeepCopy() *SlackChannelSpec {
	if in == nil {
		return nil
	}
	out := new(SlackChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepContextPolicy) DeepCopyInto(out *StepContextPolicy) {
	*out = *in
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(ContextCompressConfig)
		**out = **in
	}
	if in.Extract != nil {
		in, out := &in.Extract, &out.Extract
		*out = new(ContextExtractConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepContextPolicy.
func (in *StepContextPolicy) DeepCopy() *StepContextPolicy {
	if in == nil {
		return nil
	}
	out := new(StepContextPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepValidation) DeepCopyInto(out *StepValidation) {
	*out = *in
	if in.RejectPatterns != nil {
		in, out := &in.RejectPatterns, &out.RejectPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepValidation.
func (in *StepValidation) DeepCopy() *StepValidation {
	if in == nil {
		return nil
	}
	out := new(StepValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmAgent) DeepCopyInto(out *SwarmAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmAgent.
func (in *SwarmAgent) DeepCopy() *SwarmAgent {
	if in == nil {
		return nil
	}
	out := new(SwarmAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmAgentAutoscaling) DeepCopyInto(out *SwarmAgentAutoscaling) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetPendingTasks != nil {
		in, out := &in.TargetPendingTasks, &out.TargetPendingTasks
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmAgentAutoscaling.
func (in *SwarmAgentAutoscaling) DeepCopy() *SwarmAgentAutoscaling {
	if in == nil {
		return nil
	}
	out := new(SwarmAgentAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmAgentList) DeepCopyInto(out *SwarmAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwarmAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmAgentList.
func (in *SwarmAgentList) DeepCopy() *SwarmAgentList {
	if in == nil {
		return nil
	}
	out := new(SwarmAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmAgentMCPStatus) DeepCopyInto(out *SwarmAgentMCPStatus) {
	*out = *in
	if in.LastCheck != nil {
		in, out := &in.LastCheck, &out.LastCheck
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmAgentMCPStatus.
func (in *SwarmAgentMCPStatus) DeepCopy() *SwarmAgentMCPStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmAgentMCPStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmAgentSpec) DeepCopyInto(out *SwarmAgentSpec) {
	*out = *in
	if in.Prompt != nil {
		in, out := &in.Prompt, &out.Prompt
		*out = new(AgentPrompt)
		(*in).DeepCopyInto(*out)
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]AgentCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = new(AgentTools)
		(*in).DeepCopyInto(*out)
	}
	if in.Agents != nil {
		in, out := &in.Agents, &out.Agents
		*out = make([]AgentConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(AgentGuardrails)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(AgentRuntime)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistryRef != nil {
		in, out := &in.RegistryRef, &out.RegistryRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.APIKeyRef != nil {
		in, out := &in.APIKeyRef, &out.APIKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = new(AgentPlugins)
		(*in).DeepCopyInto(*out)
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(AgentObservability)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmAgentSpec.
func (in *SwarmAgentSpec) DeepCopy() *SwarmAgentSpec {
	if in == nil {
		return nil
	}
	out := new(SwarmAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmAgentStatus) DeepCopyInto(out *SwarmAgentStatus) {
	*out = *in
	if in.DesiredReplicas != nil {
		in, out := &in.DesiredReplicas, &out.DesiredReplicas
		*out = new(int32)
		**out = **in
	}
	if in.PendingTasks != nil {
		in, out := &in.PendingTasks, &out.PendingTasks
		*out = new(int32)
		**out = **in
	}
	if in.DailyTokenUsage != nil {
		in, out := &in.DailyTokenUsage, &out.DailyTokenUsage
		*out = new(TokenUsage)
		**out = **in
	}
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make([]SwarmAgentMCPStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExposedMCPCapabilities != nil {
		in, out := &in.ExposedMCPCapabilities, &out.ExposedMCPCapabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmAgentStatus.
func (in *SwarmAgentStatus) DeepCopy() *SwarmAgentStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmBudget) DeepCopyInto(out *SwarmBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmBudget.
func (in *SwarmBudget) DeepCopy() *SwarmBudget {
	if in == nil {
		return nil
	}
	out := new(SwarmBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmBudgetList) DeepCopyInto(out *SwarmBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwarmBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmBudgetList.
func (in *SwarmBudgetList) DeepCopy() *SwarmBudgetList {
	if in == nil {
		return nil
	}
	out := new(SwarmBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmBudgetSelector) DeepCopyInto(out *SwarmBudgetSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmBudgetSelector.
func (in *SwarmBudgetSelector) DeepCopy() *SwarmBudgetSelector {
	if in == nil {
		return nil
	}
	out := new(SwarmBudgetSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmBudgetSpec) DeepCopyInto(out *SwarmBudgetSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.NotifyRef != nil {
		in, out := &in.NotifyRef, &out.NotifyRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmBudgetSpec.
func (in *SwarmBudgetSpec) DeepCopy() *SwarmBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(SwarmBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmBudgetStatus) DeepCopyInto(out *SwarmBudgetStatus) {
	*out = *in
	if in.PeriodStart != nil {
		in, out := &in.PeriodStart, &out.PeriodStart
		*out = (*in).DeepCopy()
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmBudgetStatus.
func (in *SwarmBudgetStatus) DeepCopy() *SwarmBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmBudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmEvent) DeepCopyInto(out *SwarmEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmEvent.
func (in *SwarmEvent) DeepCopy() *SwarmEvent {
	if in == nil {
		return nil
	}
	out := new(SwarmEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmEventList) DeepCopyInto(out *SwarmEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwarmEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmEventList.
func (in *SwarmEventList) DeepCopy() *SwarmEventList {
	if in == nil {
		return nil
	}
	out := new(SwarmEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmEventSource) DeepCopyInto(out *SwarmEventSource) {
	*out = *in
	if in.TeamOutput != nil {
		in, out := &in.TeamOutput, &out.TeamOutput
		*out = new(TeamOutputSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmEventSource.
func (in *SwarmEventSource) DeepCopy() *SwarmEventSource {
	if in == nil {
		return nil
	}
	out := new(SwarmEventSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmEventSpec) DeepCopyInto(out *SwarmEventSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]SwarmEventTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmEventSpec.
func (in *SwarmEventSpec) DeepCopy() *SwarmEventSpec {
	if in == nil {
		return nil
	}
	out := new(SwarmEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmEventStatus) DeepCopyInto(out *SwarmEventStatus) {
	*out = *in
	if in.LastFiredAt != nil {
		in, out := &in.LastFiredAt, &out.LastFiredAt
		*out = (*in).DeepCopy()
	}
	if in.NextFireAt != nil {
		in, out := &in.NextFireAt, &out.NextFireAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmEventStatus.
func (in *SwarmEventStatus) DeepCopy() *SwarmEventStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmEventStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmEventTarget) DeepCopyInto(out *SwarmEventTarget) {
	*out = *in
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmEventTarget.
func (in *SwarmEventTarget) DeepCopy() *SwarmEventTarget {
	if in == nil {
		return nil
	}
	out := new(SwarmEventTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmFlowStepStatus) DeepCopyInto(out *SwarmFlowStepStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.TokenUsage != nil {
		in, out := &in.TokenUsage, &out.TokenUsage
		*out = new(TokenUsage)
		**out = **in
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmFlowStepStatus.
func (in *SwarmFlowStepStatus) DeepCopy() *SwarmFlowStepStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmFlowStepStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmMemory) DeepCopyInto(out *SwarmMemory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmMemory.
func (in *SwarmMemory) DeepCopy() *SwarmMemory {
	if in == nil {
		return nil
	}
	out := new(SwarmMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmMemory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmMemoryList) DeepCopyInto(out *SwarmMemoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwarmMemory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmMemoryList.
func (in *SwarmMemoryList) DeepCopy() *SwarmMemoryList {
	if in == nil {
		return nil
	}
	out := new(SwarmMemoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmMemoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmMemorySpec) DeepCopyInto(out *SwarmMemorySpec) {
	*out = *in
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(RedisMemoryConfig)
		**out = **in
	}
	if in.VectorStore != nil {
		in, out := &in.VectorStore, &out.VectorStore
		*out = new(VectorStoreMemoryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Embedding != nil {
		in, out := &in.Embedding, &out.Embedding
		*out = new(EmbeddingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmMemorySpec.
func (in *SwarmMemorySpec) DeepCopy() *SwarmMemorySpec {
	if in == nil {
		return nil
	}
	out := new(SwarmMemorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmMemoryStatus) DeepCopyInto(out *SwarmMemoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmMemoryStatus.
func (in *SwarmMemoryStatus) DeepCopy() *SwarmMemoryStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmMemoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmNotify) DeepCopyInto(out *SwarmNotify) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmNotify.
func (in *SwarmNotify) DeepCopy() *SwarmNotify {
	if in == nil {
		return nil
	}
	out := new(SwarmNotify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmNotify) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmNotifyList) DeepCopyInto(out *SwarmNotifyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwarmNotify, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmNotifyList.
func (in *SwarmNotifyList) DeepCopy() *SwarmNotifyList {
	if in == nil {
		return nil
	}
	out := new(SwarmNotifyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmNotifyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmNotifySpec) DeepCopyInto(out *SwarmNotifySpec) {
	*out = *in
	if in.On != nil {
		in, out := &in.On, &out.On
		*out = make([]NotifyEvent, len(*in))
		copy(*out, *in)
	}
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]NotifyChannelSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmNotifySpec.
func (in *SwarmNotifySpec) DeepCopy() *SwarmNotifySpec {
	if in == nil {
		return nil
	}
	out := new(SwarmNotifySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmNotifyStatus) DeepCopyInto(out *SwarmNotifyStatus) {
	*out = *in
	if in.LastDispatches != nil {
		in, out := &in.LastDispatches, &out.LastDispatches
		*out = make([]NotifyDispatchResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmNotifyStatus.
func (in *SwarmNotifyStatus) DeepCopy() *SwarmNotifyStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmNotifyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRegistry) DeepCopyInto(out *SwarmRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRegistry.
func (in *SwarmRegistry) DeepCopy() *SwarmRegistry {
	if in == nil {
		return nil
	}
	out := new(SwarmRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRegistryList) DeepCopyInto(out *SwarmRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwarmRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRegistryList.
func (in *SwarmRegistryList) DeepCopy() *SwarmRegistryList {
	if in == nil {
		return nil
	}
	out := new(SwarmRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRegistryPolicy) DeepCopyInto(out *SwarmRegistryPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRegistryPolicy.
func (in *SwarmRegistryPolicy) DeepCopy() *SwarmRegistryPolicy {
	if in == nil {
		return nil
	}
	out := new(SwarmRegistryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRegistrySpec) DeepCopyInto(out *SwarmRegistrySpec) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(SwarmRegistryPolicy)
		**out = **in
	}
	if in.MCPBindings != nil {
		in, out := &in.MCPBindings, &out.MCPBindings
		*out = make([]MCPBinding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRegistrySpec.
func (in *SwarmRegistrySpec) DeepCopy() *SwarmRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(SwarmRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRegistryStatus) DeepCopyInto(out *SwarmRegistryStatus) {
	*out = *in
	if in.Fleet != nil {
		in, out := &in.Fleet, &out.Fleet
		*out = make([]AgentFleetEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRebuild != nil {
		in, out := &in.LastRebuild, &out.LastRebuild
		*out = (*in).DeepCopy()
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]IndexedCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRegistryStatus.
func (in *SwarmRegistryStatus) DeepCopy() *SwarmRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRun) DeepCopyInto(out *SwarmRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRun.
func (in *SwarmRun) DeepCopy() *SwarmRun {
	if in == nil {
		return nil
	}
	out := new(SwarmRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRunList) DeepCopyInto(out *SwarmRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwarmRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRunList.
func (in *SwarmRunList) DeepCopy() *SwarmRunList {
	if in == nil {
		return nil
	}
	out := new(SwarmRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRunSpec) DeepCopyInto(out *SwarmRunSpec) {
	*out = *in
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Pipeline != nil {
		in, out := &in.Pipeline, &out.Pipeline
		*out = make([]SwarmTeamPipelineStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultContextPolicy != nil {
		in, out := &in.DefaultContextPolicy, &out.DefaultContextPolicy
		*out = new(StepContextPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]SwarmTeamRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = new(SwarmTeamRoutingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRunSpec.
func (in *SwarmRunSpec) DeepCopy() *SwarmRunSpec {
	if in == nil {
		return nil
	}
	out := new(SwarmRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmRunStatus) DeepCopyInto(out *SwarmRunStatus) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]SwarmFlowStepStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.TotalTokenUsage != nil {
		in, out := &in.TotalTokenUsage, &out.TotalTokenUsage
		*out = new(TokenUsage)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmRunStatus.
func (in *SwarmRunStatus) DeepCopy() *SwarmRunStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmSettings) DeepCopyInto(out *SwarmSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmSettings.
func (in *SwarmSettings) DeepCopy() *SwarmSettings {
	if in == nil {
		return nil
	}
	out := new(SwarmSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmSettingsList) DeepCopyInto(out *SwarmSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwarmSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmSettingsList.
func (in *SwarmSettingsList) DeepCopy() *SwarmSettingsList {
	if in == nil {
		return nil
	}
	out := new(SwarmSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmSettingsSecurity) DeepCopyInto(out *SwarmSettingsSecurity) {
	*out = *in
	if in.MCPAllowlist != nil {
		in, out := &in.MCPAllowlist, &out.MCPAllowlist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmSettingsSecurity.
func (in *SwarmSettingsSecurity) DeepCopy() *SwarmSettingsSecurity {
	if in == nil {
		return nil
	}
	out := new(SwarmSettingsSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmSettingsSpec) DeepCopyInto(out *SwarmSettingsSpec) {
	*out = *in
	if in.Fragments != nil {
		in, out := &in.Fragments, &out.Fragments
		*out = make([]PromptFragment, len(*in))
		copy(*out, *in)
	}
	if in.PromptFragments != nil {
		in, out := &in.PromptFragments, &out.PromptFragments
		*out = new(PromptFragments)
		**out = **in
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SwarmSettingsSecurity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmSettingsSpec.
func (in *SwarmSettingsSpec) DeepCopy() *SwarmSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(SwarmSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmSettingsStatus) DeepCopyInto(out *SwarmSettingsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmSettingsStatus.
func (in *SwarmSettingsStatus) DeepCopy() *SwarmSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmSettingsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeam) DeepCopyInto(out *SwarmTeam) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeam.
func (in *SwarmTeam) DeepCopy() *SwarmTeam {
	if in == nil {
		return nil
	}
	out := new(SwarmTeam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmTeam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamAutoscaling) DeepCopyInto(out *SwarmTeamAutoscaling) {
	*out = *in
	if in.ScaleToZero != nil {
		in, out := &in.ScaleToZero, &out.ScaleToZero
		*out = new(SwarmTeamScaleToZero)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamAutoscaling.
func (in *SwarmTeamAutoscaling) DeepCopy() *SwarmTeamAutoscaling {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamInputSpec) DeepCopyInto(out *SwarmTeamInputSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamInputSpec.
func (in *SwarmTeamInputSpec) DeepCopy() *SwarmTeamInputSpec {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamLimits) DeepCopyInto(out *SwarmTeamLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamLimits.
func (in *SwarmTeamLimits) DeepCopy() *SwarmTeamLimits {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamList) DeepCopyInto(out *SwarmTeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwarmTeam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamList.
func (in *SwarmTeamList) DeepCopy() *SwarmTeamList {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwarmTeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamPipelineStep) DeepCopyInto(out *SwarmTeamPipelineStep) {
	*out = *in
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Loop != nil {
		in, out := &in.Loop, &out.Loop
		*out = new(LoopSpec)
		**out = **in
	}
	if in.Validate != nil {
		in, out := &in.Validate, &out.Validate
		*out = new(StepValidation)
		(*in).DeepCopyInto(*out)
	}
	if in.OutputArtifacts != nil {
		in, out := &in.OutputArtifacts, &out.OutputArtifacts
		*out = make([]ArtifactSpec, len(*in))
		copy(*out, *in)
	}
	if in.InputArtifacts != nil {
		in, out := &in.InputArtifacts, &out.InputArtifacts
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RegistryLookup != nil {
		in, out := &in.RegistryLookup, &out.RegistryLookup
		*out = new(RegistryLookupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ContextPolicy != nil {
		in, out := &in.ContextPolicy, &out.ContextPolicy
		*out = new(StepContextPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamPipelineStep.
func (in *SwarmTeamPipelineStep) DeepCopy() *SwarmTeamPipelineStep {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamPipelineStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamRole) DeepCopyInto(out *SwarmTeamRole) {
	*out = *in
	if in.SystemPromptRef != nil {
		in, out := &in.SystemPromptRef, &out.SystemPromptRef
		*out = new(SystemPromptSource)
		(*in).DeepCopyInto(*out)
	}
	if in.MCPServers != nil {
		in, out := &in.MCPServers, &out.MCPServers
		*out = make([]MCPToolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]WebhookToolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(GuardrailLimits)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(SwarmAgentAutoscaling)
		(*in).DeepCopyInto(*out)
	}
	if in.CanDelegate != nil {
		in, out := &in.CanDelegate, &out.CanDelegate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SettingsRefs != nil {
		in, out := &in.SettingsRefs, &out.SettingsRefs
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamRole.
func (in *SwarmTeamRole) DeepCopy() *SwarmTeamRole {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamRoleStatus) DeepCopyInto(out *SwarmTeamRoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamRoleStatus.
func (in *SwarmTeamRoleStatus) DeepCopy() *SwarmTeamRoleStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamRoutingSpec) DeepCopyInto(out *SwarmTeamRoutingSpec) {
	*out = *in
	if in.RegistryRef != nil {
		in, out := &in.RegistryRef, &out.RegistryRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamRoutingSpec.
func (in *SwarmTeamRoutingSpec) DeepCopy() *SwarmTeamRoutingSpec {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamRoutingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamScaleToZero) DeepCopyInto(out *SwarmTeamScaleToZero) {
	*out = *in
	if in.AfterSeconds != nil {
		in, out := &in.AfterSeconds, &out.AfterSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamScaleToZero.
func (in *SwarmTeamScaleToZero) DeepCopy() *SwarmTeamScaleToZero {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamScaleToZero)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamSpec) DeepCopyInto(out *SwarmTeamSpec) {
	*out = *in
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]SwarmTeamInputSpec, len(*in))
		copy(*out, *in)
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(SwarmTeamLimits)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]SwarmTeamRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pipeline != nil {
		in, out := &in.Pipeline, &out.Pipeline
		*out = make([]SwarmTeamPipelineStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultContextPolicy != nil {
		in, out := &in.DefaultContextPolicy, &out.DefaultContextPolicy
		*out = new(StepContextPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.SuccessfulRunsHistoryLimit != nil {
		in, out := &in.SuccessfulRunsHistoryLimit, &out.SuccessfulRunsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedRunsHistoryLimit != nil {
		in, out := &in.FailedRunsHistoryLimit, &out.FailedRunsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.RunRetainFor != nil {
		in, out := &in.RunRetainFor, &out.RunRetainFor
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.NotifyRef != nil {
		in, out := &in.NotifyRef, &out.NotifyRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.BudgetRef != nil {
		in, out := &in.BudgetRef, &out.BudgetRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.ArtifactStore != nil {
		in, out := &in.ArtifactStore, &out.ArtifactStore
		*out = new(ArtifactStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(SwarmTeamAutoscaling)
		(*in).DeepCopyInto(*out)
	}
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = new(SwarmTeamRoutingSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamSpec.
func (in *SwarmTeamSpec) DeepCopy() *SwarmTeamSpec {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwarmTeamStatus) DeepCopyInto(out *SwarmTeamStatus) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]SwarmTeamRoleStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastActiveTime != nil {
		in, out := &in.LastActiveTime, &out.LastActiveTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwarmTeamStatus.
func (in *SwarmTeamStatus) DeepCopy() *SwarmTeamStatus {
	if in == nil {
		return nil
	}
	out := new(SwarmTeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPromptSource) DeepCopyInto(out *SystemPromptSource) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPromptSource.
func (in *SystemPromptSource) DeepCopy() *SystemPromptSource {
	if in == nil {
		return nil
	}
	out := new(SystemPromptSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamOutputSource) DeepCopyInto(out *TeamOutputSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamOutputSource.
func (in *TeamOutputSource) DeepCopy() *TeamOutputSource {
	if in == nil {
		return nil
	}
	out := new(TeamOutputSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenUsage) DeepCopyInto(out *TokenUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenUsage.
func (in *TokenUsage) DeepCopy() *TokenUsage {
	if in == nil {
		return nil
	}
	out := new(TokenUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolPermissions) DeepCopyInto(out *ToolPermissions) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Trust != nil {
		in, out := &in.Trust, &out.Trust
		*out = new(ToolTrustPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolPermissions.
func (in *ToolPermissions) DeepCopy() *ToolPermissions {
	if in == nil {
		return nil
	}
	out := new(ToolPermissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolTrustPolicy) DeepCopyInto(out *ToolTrustPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolTrustPolicy.
func (in *ToolTrustPolicy) DeepCopy() *ToolTrustPolicy {
	if in == nil {
		return nil
	}
	out := new(ToolTrustPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorStoreMemoryConfig) DeepCopyInto(out *VectorStoreMemoryConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorStoreMemoryConfig.
func (in *VectorStoreMemoryConfig) DeepCopy() *VectorStoreMemoryConfig {
	if in == nil {
		return nil
	}
	out := new(VectorStoreMemoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookChannelSpec) DeepCopyInto(out *WebhookChannelSpec) {
	*out = *in
	if in.URLFrom != nil {
		in, out := &in.URLFrom, &out.URLFrom
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]WebhookHeader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookChannelSpec.
func (in *WebhookChannelSpec) DeepCopy() *WebhookChannelSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookHeader) DeepCopyInto(out *WebhookHeader) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookHeader.
func (in *WebhookHeader) DeepCopy() *WebhookHeader {
	if in == nil {
		return nil
	}
	out := new(WebhookHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookToolSpec) DeepCopyInto(out *WebhookToolSpec) {
	*out = *in
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookToolSpec.
func (in *WebhookToolSpec) DeepCopy() *WebhookToolSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookToolSpec)
	in.DeepCopyInto(out)
	return out
}
