// Copyright 2026. Licensed under the Apache License, Version 2.0.
//
// swarm.plugin.v1 defines the gRPC contract between the swarm-agent core and
// external plugin services (RFC-0025). Any language that can generate gRPC
// stubs from this file can implement a swarm plugin.
//
// Message flow for LLMProvider.RunTask (bidirectional stream):
//
//   core  → plugin : RunTaskMessage{init}          (opens the stream)
//   plugin → core  : RunTaskMessage{chunk}         (zero or more streaming tokens)
//   plugin → core  : RunTaskMessage{tool_call}     (zero or more tool invocations)
//   core  → plugin : RunTaskMessage{tool_result}   (one per tool_call)
//   plugin → core  : RunTaskMessage{result}        (exactly one, closes the stream)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/pluginv1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMProvider_RunTask_FullMethodName = "/swarm.plugin.v1.LLMProvider/RunTask"
)

// LLMProviderClient is the client API for LLMProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMProviderClient interface {
	// RunTask drives a full agentic task over a bidirectional stream.
	// The core sends one RunTaskRequest to open the stream, then responds to
	// ToolCallRequest messages from the plugin. The plugin sends Chunk messages
	// for streaming tokens and a single Result message to close the stream.
	RunTask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunTaskMessage, RunTaskMessage], error)
}

type lLMProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMProviderClient(cc grpc.ClientConnInterface) LLMProviderClient {
	return &lLMProviderClient{cc}
}

func (c *lLMProviderClient) RunTask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunTaskMessage, RunTaskMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LLMProvider_ServiceDesc.Streams[0], LLMProvider_RunTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunTaskMessage, RunTaskMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMProvider_RunTaskClient = grpc.BidiStreamingClient[RunTaskMessage, RunTaskMessage]

// LLMProviderServer is the server API for LLMProvider service.
// All implementations must embed UnimplementedLLMProviderServer
// for forward compatibility.
type LLMProviderServer interface {
	// RunTask drives a full agentic task over a bidirectional stream.
	// The core sends one RunTaskRequest to open the stream, then responds to
	// ToolCallRequest messages from the plugin. The plugin sends Chunk messages
	// for streaming tokens and a single Result message to close the stream.
	RunTask(grpc.BidiStreamingServer[RunTaskMessage, RunTaskMessage]) error
	mustEmbedUnimplementedLLMProviderServer()
}

// UnimplementedLLMProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMProviderServer struct{}

func (UnimplementedLLMProviderServer) RunTask(grpc.BidiStreamingServer[RunTaskMessage, RunTaskMessage]) error {
	return status.Error(codes.Unimplemented, "method RunTask not implemented")
}
func (UnimplementedLLMProviderServer) mustEmbedUnimplementedLLMProviderServer() {}
func (UnimplementedLLMProviderServer) testEmbeddedByValue()                     {}

// UnsafeLLMProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMProviderServer will
// result in compilation errors.
type UnsafeLLMProviderServer interface {
	mustEmbedUnimplementedLLMProviderServer()
}

func RegisterLLMProviderServer(s grpc.ServiceRegistrar, srv LLMProviderServer) {
	// If the following call panics, it indicates UnimplementedLLMProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMProvider_ServiceDesc, srv)
}

func _LLMProvider_RunTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LLMProviderServer).RunTask(&grpc.GenericServerStream[RunTaskMessage, RunTaskMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LLMProvider_RunTaskServer = grpc.BidiStreamingServer[RunTaskMessage, RunTaskMessage]

// LLMProvider_ServiceDesc is the grpc.ServiceDesc for LLMProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.plugin.v1.LLMProvider",
	HandlerType: (*LLMProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunTask",
			Handler:       _LLMProvider_RunTask_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/pluginv1/plugin.proto",
}

const (
	TaskQueue_Submit_FullMethodName  = "/swarm.plugin.v1.TaskQueue/Submit"
	TaskQueue_Poll_FullMethodName    = "/swarm.plugin.v1.TaskQueue/Poll"
	TaskQueue_Ack_FullMethodName     = "/swarm.plugin.v1.TaskQueue/Ack"
	TaskQueue_Nack_FullMethodName    = "/swarm.plugin.v1.TaskQueue/Nack"
	TaskQueue_Results_FullMethodName = "/swarm.plugin.v1.TaskQueue/Results"
	TaskQueue_Cancel_FullMethodName  = "/swarm.plugin.v1.TaskQueue/Cancel"
)

// TaskQueueClient is the client API for TaskQueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskQueueClient interface {
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
	Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error)
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
	Nack(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*NackResponse, error)
	Results(ctx context.Context, in *ResultsRequest, opts ...grpc.CallOption) (*ResultsResponse, error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
}

type taskQueueClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskQueueClient(cc grpc.ClientConnInterface) TaskQueueClient {
	return &taskQueueClient{cc}
}

func (c *taskQueueClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponse)
	err := c.cc.Invoke(ctx, TaskQueue_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskQueueClient) Poll(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (*PollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollResponse)
	err := c.cc.Invoke(ctx, TaskQueue_Poll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskQueueClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, TaskQueue_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskQueueClient) Nack(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*NackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NackResponse)
	err := c.cc.Invoke(ctx, TaskQueue_Nack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskQueueClient) Results(ctx context.Context, in *ResultsRequest, opts ...grpc.CallOption) (*ResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultsResponse)
	err := c.cc.Invoke(ctx, TaskQueue_Results_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskQueueClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, TaskQueue_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskQueueServer is the server API for TaskQueue service.
// All implementations must embed UnimplementedTaskQueueServer
// for forward compatibility.
type TaskQueueServer interface {
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
	Poll(context.Context, *PollRequest) (*PollResponse, error)
	Ack(context.Context, *AckRequest) (*AckResponse, error)
	Nack(context.Context, *NackRequest) (*NackResponse, error)
	Results(context.Context, *ResultsRequest) (*ResultsResponse, error)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	mustEmbedUnimplementedTaskQueueServer()
}

// UnimplementedTaskQueueServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskQueueServer struct{}

func (UnimplementedTaskQueueServer) Submit(context.Context, *SubmitRequest) (*SubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedTaskQueueServer) Poll(context.Context, *PollRequest) (*PollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Poll not implemented")
}
func (UnimplementedTaskQueueServer) Ack(context.Context, *AckRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedTaskQueueServer) Nack(context.Context, *NackRequest) (*NackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Nack not implemented")
}
func (UnimplementedTaskQueueServer) Results(context.Context, *ResultsRequest) (*ResultsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Results not implemented")
}
func (UnimplementedTaskQueueServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedTaskQueueServer) mustEmbedUnimplementedTaskQueueServer() {}
func (UnimplementedTaskQueueServer) testEmbeddedByValue()                   {}

// UnsafeTaskQueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskQueueServer will
// result in compilation errors.
type UnsafeTaskQueueServer interface {
	mustEmbedUnimplementedTaskQueueServer()
}

func RegisterTaskQueueServer(s grpc.ServiceRegistrar, srv TaskQueueServer) {
	// If the following call panics, it indicates UnimplementedTaskQueueServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskQueue_ServiceDesc, srv)
}

func _TaskQueue_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskQueueServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskQueue_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskQueueServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskQueue_Poll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskQueueServer).Poll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskQueue_Poll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskQueueServer).Poll(ctx, req.(*PollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskQueue_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskQueueServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskQueue_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskQueueServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskQueue_Nack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskQueueServer).Nack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskQueue_Nack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskQueueServer).Nack(ctx, req.(*NackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskQueue_Results_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskQueueServer).Results(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskQueue_Results_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskQueueServer).Results(ctx, req.(*ResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskQueue_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskQueueServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskQueue_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskQueueServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskQueue_ServiceDesc is the grpc.ServiceDesc for TaskQueue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskQueue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.plugin.v1.TaskQueue",
	HandlerType: (*TaskQueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _TaskQueue_Submit_Handler,
		},
		{
			MethodName: "Poll",
			Handler:    _TaskQueue_Poll_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _TaskQueue_Ack_Handler,
		},
		{
			MethodName: "Nack",
			Handler:    _TaskQueue_Nack_Handler,
		},
		{
			MethodName: "Results",
			Handler:    _TaskQueue_Results_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _TaskQueue_Cancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pluginv1/plugin.proto",
}
