// Copyright 2026. Licensed under the Apache License, Version 2.0.
//
// swarm.plugin.v1 defines the gRPC contract between the swarm-agent core and
// external plugin services (RFC-0025). Any language that can generate gRPC
// stubs from this file can implement a swarm plugin.
//
// Message flow for LLMProvider.RunTask (bidirectional stream):
//
//   core  → plugin : RunTaskMessage{init}          (opens the stream)
//   plugin → core  : RunTaskMessage{chunk}         (zero or more streaming tokens)
//   plugin → core  : RunTaskMessage{tool_call}     (zero or more tool invocations)
//   core  → plugin : RunTaskMessage{tool_result}   (one per tool_call)
//   plugin → core  : RunTaskMessage{result}        (exactly one, closes the stream)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/pluginv1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunTaskMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RunTaskMessage_Init
	//	*RunTaskMessage_ToolCall
	//	*RunTaskMessage_ToolResult
	//	*RunTaskMessage_Chunk
	//	*RunTaskMessage_Result
	Payload       isRunTaskMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskMessage) Reset() {
	*x = RunTaskMessage{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskMessage) ProtoMessage() {}

func (x *RunTaskMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskMessage.ProtoReflect.Descriptor instead.
func (*RunTaskMessage) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *RunTaskMessage) GetPayload() isRunTaskMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RunTaskMessage) GetInit() *RunTaskRequest {
	if x != nil {
		if x, ok := x.Payload.(*RunTaskMessage_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *RunTaskMessage) GetToolCall() *ToolCallRequest {
	if x != nil {
		if x, ok := x.Payload.(*RunTaskMessage_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *RunTaskMessage) GetToolResult() *ToolCallResult {
	if x != nil {
		if x, ok := x.Payload.(*RunTaskMessage_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *RunTaskMessage) GetChunk() *Chunk {
	if x != nil {
		if x, ok := x.Payload.(*RunTaskMessage_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *RunTaskMessage) GetResult() *Result {
	if x != nil {
		if x, ok := x.Payload.(*RunTaskMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isRunTaskMessage_Payload interface {
	isRunTaskMessage_Payload()
}

type RunTaskMessage_Init struct {
	Init *RunTaskRequest `protobuf:"bytes,1,opt,name=init,proto3,oneof"` // core → plugin (first message)
}

type RunTaskMessage_ToolCall struct {
	ToolCall *ToolCallRequest `protobuf:"bytes,2,opt,name=tool_call,json=toolCall,proto3,oneof"` // plugin → core
}

type RunTaskMessage_ToolResult struct {
	ToolResult *ToolCallResult `protobuf:"bytes,3,opt,name=tool_result,json=toolResult,proto3,oneof"` // core → plugin
}

type RunTaskMessage_Chunk struct {
	Chunk *Chunk `protobuf:"bytes,4,opt,name=chunk,proto3,oneof"` // plugin → core (streaming token)
}

type RunTaskMessage_Result struct {
	Result *Result `protobuf:"bytes,5,opt,name=result,proto3,oneof"` // plugin → core (terminal, closes stream)
}

func (*RunTaskMessage_Init) isRunTaskMessage_Payload() {}

func (*RunTaskMessage_ToolCall) isRunTaskMessage_Payload() {}

func (*RunTaskMessage_ToolResult) isRunTaskMessage_Payload() {}

func (*RunTaskMessage_Chunk) isRunTaskMessage_Payload() {}

func (*RunTaskMessage_Result) isRunTaskMessage_Payload() {}

type RunTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Tools         []*Tool                `protobuf:"bytes,6,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskRequest) Reset() {
	*x = RunTaskRequest{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskRequest) ProtoMessage() {}

func (x *RunTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskRequest.ProtoReflect.Descriptor instead.
func (*RunTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *RunTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RunTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *RunTaskRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *RunTaskRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RunTaskRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *RunTaskRequest) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   []byte                 `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"` // JSON Schema as raw bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetInputSchema() []byte {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

type ToolCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input         []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"` // JSON-encoded tool arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallRequest) Reset() {
	*x = ToolCallRequest{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallRequest) ProtoMessage() {}

func (x *ToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallRequest.ProtoReflect.Descriptor instead.
func (*ToolCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCallRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type ToolCallResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` // non-empty when tool execution failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallResult) Reset() {
	*x = ToolCallResult{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallResult) ProtoMessage() {}

func (x *ToolCallResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallResult.ProtoReflect.Descriptor instead.
func (*ToolCallResult) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ToolCallResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCallResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolCallResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Chunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Result struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Output       string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	InputTokens  int64                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens int64                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	// Non-empty signals task failure. Prefix with "permanent failure: " to
	// dead-letter immediately without retrying (e.g. billing exhausted, bad key).
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Result) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Result) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Result) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Task) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SubmitRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMs     int32                  `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *PollRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *PollResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	InputTokens   int64                  `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int64                  `protobuf:"varint,4,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *AckRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *AckRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AckRequest) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *AckRequest) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{13}
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *NackRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *NackRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackResponse) Reset() {
	*x = NackResponse{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackResponse) ProtoMessage() {}

func (x *NackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackResponse.ProtoReflect.Descriptor instead.
func (*NackResponse) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{15}
}

type ResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []string               `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultsRequest) Reset() {
	*x = ResultsRequest{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsRequest) ProtoMessage() {}

func (x *ResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsRequest.ProtoReflect.Descriptor instead.
func (*ResultsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ResultsRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type ResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TaskResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultsResponse) Reset() {
	*x = ResultsResponse{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsResponse) ProtoMessage() {}

func (x *ResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsResponse.ProtoReflect.Descriptor instead.
func (*ResultsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ResultsResponse) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	InputTokens   int64                  `protobuf:"varint,4,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int64                  `protobuf:"varint,5,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TaskResult) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []string               `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *CancelRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pluginv1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_pluginv1_plugin_proto_rawDescGZIP(), []int{20}
}

var File_proto_pluginv1_plugin_proto protoreflect.FileDescriptor

const file_proto_pluginv1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/pluginv1/plugin.proto\x12\x0fswarm.plugin.v1\"\xba\x02\n" +
	"\x0eRunTaskMessage\x125\n" +
	"\x04init\x18\x01 \x01(\v2\x1f.swarm.plugin.v1.RunTaskRequestH\x00R\x04init\x12?\n" +
	"\ttool_call\x18\x02 \x01(\v2 .swarm.plugin.v1.ToolCallRequestH\x00R\btoolCall\x12B\n" +
	"\vtool_result\x18\x03 \x01(\v2\x1f.swarm.plugin.v1.ToolCallResultH\x00R\n" +
	"toolResult\x12.\n" +
	"\x05chunk\x18\x04 \x01(\v2\x16.swarm.plugin.v1.ChunkH\x00R\x05chunk\x121\n" +
	"\x06result\x18\x05 \x01(\v2\x17.swarm.plugin.v1.ResultH\x00R\x06resultB\t\n" +
	"\apayload\"\xc8\x01\n" +
	"\x0eRunTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12+\n" +
	"\x05tools\x18\x06 \x03(\v2\x15.swarm.plugin.v1.ToolR\x05tools\"_\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x03 \x01(\fR\vinputSchema\"]\n" +
	"\x0fToolCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\"W\n" +
	"\x0eToolCallResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x1b\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"~\n" +
	"\x06Result\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x03R\foutputTokens\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x9c\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x123\n" +
	"\x04meta\x18\x03 \x03(\v2\x1f.swarm.plugin.v1.Task.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\rSubmitRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12<\n" +
	"\x04meta\x18\x02 \x03(\v2(.swarm.plugin.v1.SubmitRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x0eSubmitResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\",\n" +
	"\vPollRequest\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\x05R\ttimeoutMs\"9\n" +
	"\fPollResponse\x12)\n" +
	"\x04task\x18\x01 \x01(\v2\x15.swarm.plugin.v1.TaskR\x04task\"\x97\x01\n" +
	"\n" +
	"AckRequest\x12)\n" +
	"\x04task\x18\x01 \x01(\v2\x15.swarm.plugin.v1.TaskR\x04task\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x04 \x01(\x03R\foutputTokens\"\r\n" +
	"\vAckResponse\"P\n" +
	"\vNackRequest\x12)\n" +
	"\x04task\x18\x01 \x01(\v2\x15.swarm.plugin.v1.TaskR\x04task\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x0e\n" +
	"\fNackResponse\"+\n" +
	"\x0eResultsRequest\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\"H\n" +
	"\x0fResultsResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.swarm.plugin.v1.TaskResultR\aresults\"\x9b\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12!\n" +
	"\finput_tokens\x18\x04 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x05 \x01(\x03R\foutputTokens\"*\n" +
	"\rCancelRequest\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\"\x10\n" +
	"\x0eCancelResponse2^\n" +
	"\vLLMProvider\x12O\n" +
	"\aRunTask\x12\x1f.swarm.plugin.v1.RunTaskMessage\x1a\x1f.swarm.plugin.v1.RunTaskMessage(\x010\x012\xbb\x03\n" +
	"\tTaskQueue\x12I\n" +
	"\x06Submit\x12\x1e.swarm.plugin.v1.SubmitRequest\x1a\x1f.swarm.plugin.v1.SubmitResponse\x12C\n" +
	"\x04Poll\x12\x1c.swarm.plugin.v1.PollRequest\x1a\x1d.swarm.plugin.v1.PollResponse\x12@\n" +
	"\x03Ack\x12\x1b.swarm.plugin.v1.AckRequest\x1a\x1c.swarm.plugin.v1.AckResponse\x12C\n" +
	"\x04Nack\x12\x1c.swarm.plugin.v1.NackRequest\x1a\x1d.swarm.plugin.v1.NackResponse\x12L\n" +
	"\aResults\x12\x1f.swarm.plugin.v1.ResultsRequest\x1a .swarm.plugin.v1.ResultsResponse\x12I\n" +
	"\x06Cancel\x12\x1e.swarm.plugin.v1.CancelRequest\x1a\x1f.swarm.plugin.v1.CancelResponseB/Z-github.com/kubeswarm/kubeswarm/proto/pluginv1b\x06proto3"

var (
	file_proto_pluginv1_plugin_proto_rawDescOnce sync.Once
	file_proto_pluginv1_plugin_proto_rawDescData []byte
)

func file_proto_pluginv1_plugin_proto_rawDescGZIP() []byte {
	file_proto_pluginv1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_pluginv1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pluginv1_plugin_proto_rawDesc), len(file_proto_pluginv1_plugin_proto_rawDesc)))
	})
	return file_proto_pluginv1_plugin_proto_rawDescData
}

var file_proto_pluginv1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_pluginv1_plugin_proto_goTypes = []any{
	(*RunTaskMessage)(nil),  // 0: swarm.plugin.v1.RunTaskMessage
	(*RunTaskRequest)(nil),  // 1: swarm.plugin.v1.RunTaskRequest
	(*Tool)(nil),            // 2: swarm.plugin.v1.Tool
	(*ToolCallRequest)(nil), // 3: swarm.plugin.v1.ToolCallRequest
	(*ToolCallResult)(nil),  // 4: swarm.plugin.v1.ToolCallResult
	(*Chunk)(nil),           // 5: swarm.plugin.v1.Chunk
	(*Result)(nil),          // 6: swarm.plugin.v1.Result
	(*Task)(nil),            // 7: swarm.plugin.v1.Task
	(*SubmitRequest)(nil),   // 8: swarm.plugin.v1.SubmitRequest
	(*SubmitResponse)(nil),  // 9: swarm.plugin.v1.SubmitResponse
	(*PollRequest)(nil),     // 10: swarm.plugin.v1.PollRequest
	(*PollResponse)(nil),    // 11: swarm.plugin.v1.PollResponse
	(*AckRequest)(nil),      // 12: swarm.plugin.v1.AckRequest
	(*AckResponse)(nil),     // 13: swarm.plugin.v1.AckResponse
	(*NackRequest)(nil),     // 14: swarm.plugin.v1.NackRequest
	(*NackResponse)(nil),    // 15: swarm.plugin.v1.NackResponse
	(*ResultsRequest)(nil),  // 16: swarm.plugin.v1.ResultsRequest
	(*ResultsResponse)(nil), // 17: swarm.plugin.v1.ResultsResponse
	(*TaskResult)(nil),      // 18: swarm.plugin.v1.TaskResult
	(*CancelRequest)(nil),   // 19: swarm.plugin.v1.CancelRequest
	(*CancelResponse)(nil),  // 20: swarm.plugin.v1.CancelResponse
	nil,                     // 21: swarm.plugin.v1.Task.MetaEntry
	nil,                     // 22: swarm.plugin.v1.SubmitRequest.MetaEntry
}
var file_proto_pluginv1_plugin_proto_depIdxs = []int32{
	1,  // 0: swarm.plugin.v1.RunTaskMessage.init:type_name -> swarm.plugin.v1.RunTaskRequest
	3,  // 1: swarm.plugin.v1.RunTaskMessage.tool_call:type_name -> swarm.plugin.v1.ToolCallRequest
	4,  // 2: swarm.plugin.v1.RunTaskMessage.tool_result:type_name -> swarm.plugin.v1.ToolCallResult
	5,  // 3: swarm.plugin.v1.RunTaskMessage.chunk:type_name -> swarm.plugin.v1.Chunk
	6,  // 4: swarm.plugin.v1.RunTaskMessage.result:type_name -> swarm.plugin.v1.Result
	2,  // 5: swarm.plugin.v1.RunTaskRequest.tools:type_name -> swarm.plugin.v1.Tool
	21, // 6: swarm.plugin.v1.Task.meta:type_name -> swarm.plugin.v1.Task.MetaEntry
	22, // 7: swarm.plugin.v1.SubmitRequest.meta:type_name -> swarm.plugin.v1.SubmitRequest.MetaEntry
	7,  // 8: swarm.plugin.v1.PollResponse.task:type_name -> swarm.plugin.v1.Task
	7,  // 9: swarm.plugin.v1.AckRequest.task:type_name -> swarm.plugin.v1.Task
	7,  // 10: swarm.plugin.v1.NackRequest.task:type_name -> swarm.plugin.v1.Task
	18, // 11: swarm.plugin.v1.ResultsResponse.results:type_name -> swarm.plugin.v1.TaskResult
	0,  // 12: swarm.plugin.v1.LLMProvider.RunTask:input_type -> swarm.plugin.v1.RunTaskMessage
	8,  // 13: swarm.plugin.v1.TaskQueue.Submit:input_type -> swarm.plugin.v1.SubmitRequest
	10, // 14: swarm.plugin.v1.TaskQueue.Poll:input_type -> swarm.plugin.v1.PollRequest
	12, // 15: swarm.plugin.v1.TaskQueue.Ack:input_type -> swarm.plugin.v1.AckRequest
	14, // 16: swarm.plugin.v1.TaskQueue.Nack:input_type -> swarm.plugin.v1.NackRequest
	16, // 17: swarm.plugin.v1.TaskQueue.Results:input_type -> swarm.plugin.v1.ResultsRequest
	19, // 18: swarm.plugin.v1.TaskQueue.Cancel:input_type -> swarm.plugin.v1.CancelRequest
	0,  // 19: swarm.plugin.v1.LLMProvider.RunTask:output_type -> swarm.plugin.v1.RunTaskMessage
	9,  // 20: swarm.plugin.v1.TaskQueue.Submit:output_type -> swarm.plugin.v1.SubmitResponse
	11, // 21: swarm.plugin.v1.TaskQueue.Poll:output_type -> swarm.plugin.v1.PollResponse
	13, // 22: swarm.plugin.v1.TaskQueue.Ack:output_type -> swarm.plugin.v1.AckResponse
	15, // 23: swarm.plugin.v1.TaskQueue.Nack:output_type -> swarm.plugin.v1.NackResponse
	17, // 24: swarm.plugin.v1.TaskQueue.Results:output_type -> swarm.plugin.v1.ResultsResponse
	20, // 25: swarm.plugin.v1.TaskQueue.Cancel:output_type -> swarm.plugin.v1.CancelResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_pluginv1_plugin_proto_init() }
func file_proto_pluginv1_plugin_proto_init() {
	if File_proto_pluginv1_plugin_proto != nil {
		return
	}
	file_proto_pluginv1_plugin_proto_msgTypes[0].OneofWrappers = []any{
		(*RunTaskMessage_Init)(nil),
		(*RunTaskMessage_ToolCall)(nil),
		(*RunTaskMessage_ToolResult)(nil),
		(*RunTaskMessage_Chunk)(nil),
		(*RunTaskMessage_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pluginv1_plugin_proto_rawDesc), len(file_proto_pluginv1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_pluginv1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_pluginv1_plugin_proto_depIdxs,
		MessageInfos:      file_proto_pluginv1_plugin_proto_msgTypes,
	}.Build()
	File_proto_pluginv1_plugin_proto = out.File
	file_proto_pluginv1_plugin_proto_goTypes = nil
	file_proto_pluginv1_plugin_proto_depIdxs = nil
}
